import { DEFAULT_BOX_SIZE } from './constants.ts';

interface GameConfig {
  id: string;
  name: string;
  generation: number;
  pokedex: string;
  region: string;
  color: string;
  boxSize: number;
  versions: string[];
  versionGroup: string;
  extraPokedexes?: string[];
}

export const GAMES: GameConfig[] = [
  {
    id: 'red-blue',
    name: 'Red / Blue',
    generation: 1,
    pokedex: 'kanto',
    region: 'Kanto',
    color: '#DC0A2D',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['red', 'blue'],
    versionGroup: 'red-blue',
  },
  {
    id: 'yellow',
    name: 'Yellow',
    generation: 1,
    pokedex: 'kanto',
    region: 'Kanto',
    color: '#F6D02F',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['yellow'],
    versionGroup: 'yellow',
  },
  {
    id: 'gold-silver',
    name: 'Gold / Silver',
    generation: 2,
    pokedex: 'original-johto',
    region: 'Johto',
    color: '#DAA520',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['gold', 'silver'],
    versionGroup: 'gold-silver',
  },
  {
    id: 'crystal',
    name: 'Crystal',
    generation: 2,
    pokedex: 'original-johto',
    region: 'Johto',
    color: '#4FD1C5',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['crystal'],
    versionGroup: 'crystal',
  },
  {
    id: 'ruby-sapphire',
    name: 'Ruby / Sapphire',
    generation: 3,
    pokedex: 'hoenn',
    region: 'Hoenn',
    color: '#A00000',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['ruby', 'sapphire'],
    versionGroup: 'ruby-sapphire',
  },
  {
    id: 'emerald',
    name: 'Emerald',
    generation: 3,
    pokedex: 'hoenn',
    region: 'Hoenn',
    color: '#4CAF50',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['emerald'],
    versionGroup: 'emerald',
  },
  {
    id: 'firered-leafgreen',
    name: 'FireRed / LeafGreen',
    generation: 3,
    pokedex: 'kanto',
    region: 'Kanto',
    color: '#FF6F00',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['firered', 'leafgreen'],
    versionGroup: 'firered-leafgreen',
  },
  {
    id: 'diamond-pearl',
    name: 'Diamond / Pearl',
    generation: 4,
    pokedex: 'original-sinnoh',
    region: 'Sinnoh',
    color: '#7986CB',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['diamond', 'pearl'],
    versionGroup: 'diamond-pearl',
  },
  {
    id: 'platinum',
    name: 'Platinum',
    generation: 4,
    pokedex: 'extended-sinnoh',
    region: 'Sinnoh',
    color: '#90A4AE',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['platinum'],
    versionGroup: 'platinum',
  },
  {
    id: 'heartgold-soulsilver',
    name: 'HeartGold / SoulSilver',
    generation: 4,
    pokedex: 'updated-johto',
    region: 'Johto',
    color: '#DAA520',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['heartgold', 'soulsilver'],
    versionGroup: 'heartgold-soulsilver',
  },
  {
    id: 'black-white',
    name: 'Black / White',
    generation: 5,
    pokedex: 'original-unova',
    region: 'Unova',
    color: '#333333',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['black', 'white'],
    versionGroup: 'black-white',
  },
  {
    id: 'black2-white2',
    name: 'Black 2 / White 2',
    generation: 5,
    pokedex: 'updated-unova',
    region: 'Unova',
    color: '#555555',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['black-2', 'white-2'],
    versionGroup: 'black-2-white-2',
  },
  {
    id: 'x-y',
    name: 'X / Y',
    generation: 6,
    pokedex: 'kalos-central',
    region: 'Kalos',
    color: '#1565C0',
    boxSize: DEFAULT_BOX_SIZE,
    extraPokedexes: ['kalos-coastal', 'kalos-mountain'],
    versions: ['x', 'y'],
    versionGroup: 'x-y',
  },
  {
    id: 'omega-ruby-alpha-sapphire',
    name: 'Omega Ruby / Alpha Sapphire',
    generation: 6,
    pokedex: 'updated-hoenn',
    region: 'Hoenn',
    color: '#C62828',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['omega-ruby', 'alpha-sapphire'],
    versionGroup: 'omega-ruby-alpha-sapphire',
  },
  {
    id: 'sun-moon',
    name: 'Sun / Moon',
    generation: 7,
    pokedex: 'original-alola',
    region: 'Alola',
    color: '#FF8F00',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['sun', 'moon'],
    versionGroup: 'sun-moon',
  },
  {
    id: 'ultra-sun-ultra-moon',
    name: 'Ultra Sun / Ultra Moon',
    generation: 7,
    pokedex: 'updated-alola',
    region: 'Alola',
    color: '#FF6F00',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['ultra-sun', 'ultra-moon'],
    versionGroup: 'ultra-sun-ultra-moon',
  },
  {
    id: 'lets-go',
    name: "Let's Go Pikachu / Eevee",
    generation: 7,
    pokedex: 'letsgo-kanto',
    region: 'Kanto',
    color: '#FDD835',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['lets-go-pikachu', 'lets-go-eevee'],
    versionGroup: 'lets-go-pikachu-lets-go-eevee',
  },
  {
    id: 'sword-shield',
    name: 'Sword / Shield',
    generation: 8,
    pokedex: 'galar',
    region: 'Galar',
    color: '#1E88E5',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['sword', 'shield'],
    versionGroup: 'sword-shield',
  },
  {
    id: 'brilliant-diamond-shining-pearl',
    name: 'Brilliant Diamond / Shining Pearl',
    generation: 8,
    pokedex: 'original-sinnoh',
    region: 'Sinnoh',
    color: '#7986CB',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['brilliant-diamond', 'shining-pearl'],
    versionGroup: 'brilliant-diamond-and-shining-pearl',
  },
  {
    id: 'legends-arceus',
    name: 'Legends: Arceus',
    generation: 8,
    pokedex: 'hisui',
    region: 'Hisui',
    color: '#5D4037',
    boxSize: DEFAULT_BOX_SIZE,
    versions: [],
    versionGroup: 'legends-arceus',
  },
  {
    id: 'scarlet-violet',
    name: 'Scarlet / Violet',
    generation: 9,
    pokedex: 'paldea',
    region: 'Paldea',
    color: '#D32F2F',
    boxSize: DEFAULT_BOX_SIZE,
    versions: ['scarlet', 'violet'],
    versionGroup: 'scarlet-violet',
  },
  {
    id: 'legends-za',
    name: 'Legends: Z-A',
    generation: 9,
    pokedex: 'kalos-central',
    region: 'Kalos',
    color: '#1565C0',
    boxSize: DEFAULT_BOX_SIZE,
    extraPokedexes: ['kalos-coastal', 'kalos-mountain'],
    versions: [],
    versionGroup: '',
  },
];

export function getGameById(id: string): GameConfig {
  return GAMES.find(g => g.id === id)!;
}
